### ISSUE TITLE
Support for mrs:NetworkStatus with dataplane type status

### ISSUE THREAD

**Issue by xi-yang** [esnet/sense-rm#39]
This will be similar to Items 3 and 4 for the SENSE-O NSIDriver feature https://github.com/esnet/StackV/issues/1150.

Referene code: https://github.com/esnet/StackV/blob/main/StackV-ejb/src/main/java/net/maxgigapop/mrs/driver/nsi/NSIService.java#L207

Run experiment with a NSIDriver backed domain, such as icair mren8700 on  [sense-o-dev.es.net](https://sense-o-dev.es.net:8443/StackV-web/portal/) to observe the modeling.

**Comment by jmacauley** [comment]
Cleaning up old closed issues.  This issue was closed with commit cd80b107c71d4578d06c23aba6ede5a5ca820487.
